name: Deploy Production Frontend

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: production
